config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}
  
  # Chemins pour les packs kibrilles
  get 'pack_kibrilles', to: 'purchase_histories#index'
  post 'purchase_kibrilles_pack', to: 'purchase_histories#create'
  
  # Chemins pour la bibliothèque
  get 'bibliotheque', to: 'library#edit'
  post 'bibliotheque', to: 'library#update', as: 'library'
  
  # chemins pour les decks
  get 'decks', to: 'deck#index'
  get 'deck', to: 'deck#show', as: 'deck'
  get 'new_deck', to: 'deck#new', as: 'new_deck' 
  post 'create_deck', to: 'deck#create', as: 'create_deck'
  get 'edit_deck/:id', to: 'deck#edit', as: 'edit_deck'
  post 'update_deck', to: 'deck#update', as: 'update_deck'
  post 'destroy_deck', to: 'deck#destroy', as: 'destroy_deck'
  
  root 'home#index'
  
  get 'gachas', to: 'gacha#index'
  post 'roll_gacha', to: 'gacha#create'
  # match "*path", to: "application#routing_error", via: :all
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 25 }
  for i in 1..50 do
    validates "card_#{i}",
      numericality: { 
        only_integer: true,
        greater_than_or_equal_to: 0
      },
      allow_blank: true
  end
end

app/controllers/deck_controller.rb
class DeckController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :deck_not_found
  before_action :find_deck, only: [:edit, :update, :destroy]
  
  def index
    @decks = current_user.decks
  end

  def new
    @deck = current_user.decks.new
  end

  def create
    @deck = current_user.decks.new(deck_params)
    @deck.card_16 = 1

    cards = 0
    @deck.each do |d|
      cards += d.send("card_#{card.id}")
    end

    if cards.in?(0..40)
      if @deck.save
        respond_to do |format|
          format.html { redirect_to decks_path, notice: 'Deck créée.' }
          format.json { redirect_to decks_path, status: 302 }
        end
      else
        respond_to do |format|
          format.html { render :new, alert: 'Erreur dans la création du deck.' }
          format.json { render json: @deck.errors, status: 422 }
        end
      end
    else
      respond_to do |format|
        format.html { render :new, alert: 'Un Deck ne peut comporter plus de 40 cartes ...' }
        format.json { render json: @deck.errors, status: 422 }
      end
    end
  end

  def edit
    @cards = Card.all
    
    fail ActiveRecord::RecordNotFound if @deck.nil?
  end

  def update
    @deck = current_user.decks.find(params[:id])
    @deck.update(deck_params)
    @deck.card_16 = 1
    
    cards = 0
    @deck.each do |d|
      cards += d.send("card_#{card.id}")
    end
    
    if cards.in?(0..40)
      if @deck.save
        respond_to do |format|
          format.html { redirect_to @deck, notice: 'Deck mis à jours.' }
          format.json { redirect_to @deck, status: 302, location: @deck }
        end
      else
        respond_to do |format|
          format.html { render :edit, alert: 'Erreur dans la sauvegarde.' }
          format.json { render json: @deck.errors, status: 422 }
        end
      end
    else
      respond_to do |format|
        format.html { render :edit, alert: 'Un Deck ne peut comporter plus de 40 cartes ...' }
        format.json { render json: @deck.errors, status: 422 }
      end
    end
  end

  def destroy
    if @deck.nil?
      fail ActiveRecord::RecordNotFound
    else
      if @deck.destroy
        respond_to do |format|
          format.html { redirect_to decks_path, notice: 'Deck supprimé.' }
          format.json { head :no_content, status: 204 }
        end
      else
        respond_to do |format|
          format.html { redirect_to @deck, alert: 'Erreur dans la suppression.' }
          format.json { render json: @deck.errors, status: 422 }
        end
      end
    end
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :card_1, :card_2, :card_3, :card_4,
                                 :card_5, :card_6, :card_7, :card_8, :card_9,
                                 :card_10, :card_11, :card_12, :card_13,
                                 :card_14, :card_15, :card_16, :card_17,
                                 :card_18, :card_19, :card_20, :card_21,
                                 :card_22, :card_23, :card_24, :card_25,
                                 :card_26, :card_27, :card_28, :card_29,
                                 :card_30, :card_31, :card_32, :card_33,
                                 :card_34, :card_35, :card_36, :card_37,
                                 :card_38, :card_39, :card_40, :card_41,
                                 :card_42, :card_43, :card_44, :card_45,
                                 :card_46, :card_47, :card_48, :card_49,
                                 :card_50)
  end
  
  def find_deck
    @deck = Deck.find(params[:id])
  end
  
  def deck_not_found
    render 'decks/deck_missing', status: 404
  end
end

app/helpers/deck_helper.rb
module DeckHelper
end

app/views/deck/deck_missing.html.erb
<h1>Your higness ? What thou seekest haven't been founded ...</h1>

app/views/deck/edit.html.erb
<div class="wrapper-bibli">
	<p>
  	<h3>
    	Nom du Deck : <%= @deck.name %>
    </h3>
  </p>

	<div class="wrapper-bibli">
		<div class="wrapper-carte">
	 		<% @cards.each do |c| %>
	   		<% if @deck.send("card_#{c.id}") %>
	   			<% if @deck.send("card_#{c.id}") > 0 %>
	       		<% for i in 1..@deck.send("card_#{c.id}") do %>
	     				<div class="carte">
	           		<%= image_tag(c.image.url(:card)) %>
	         		</div>
	       			<%= button_to("Retirer carte", { action: 'create' }, method: :post, params: {id: c.id, action: :remove},
		            data: { confirm: "Retirer 1 carte :\n#{c.name} ?" }) %><br>
	       		<% end %>
	      	<% end %>
	    	<% end %>
	 	  <% end %>
		</div>
	</div>
	  
	<div class="stats-bibli">
	 	<% total = 0 %>
	 	<% for i in 1..15 do %>
	   	<% total += @deck.send("card_#{i}") %>
	  <% end %>
	  <h3>
	   	<%= "Total Cartes : #{total} / 40" %>
    </h3>
	  <!--a href="#" class="btn btn-default">Enregistrer Deck</a-->
	</div>
</div>

app/views/deck/index.html.erb
<% @decks.each do |d| %>
  <%= link_to(d.name, edit_deck_path(d.id), class: "btn btn-primary btn-lg") %><br>
  <% counter = 0 %>
  <% for i in 1..15 do %>
    <% counter += d.send("card_#{i}") %>
  <% end %>
  <div class="stats-bibli">
    <h3><%= "Cartes : #{counter} / 40" %></h3>
  </div>
<% end %>

app/views/deck/new.html.erb
<%= form_for @deck do |d| %>
  <% if @deck.errors.any? %>
    <div id='error_explanation'>
      <h2>
        <%= pluralize(@deck.errors.count, 'error') %> prohibited this article
        from being saved:
      </h2>
      <ul>
        <% @deck.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= d.text_field :name %><br>
  </p>
  
  <% for i in 1..15 do %>
    <p>
      <%= d.number_field("deck_#{i}", step: 1) %>
    </p>
  <% end %>
  <p>
    <%= d.submit %>
  </p>
<% end %>